# Generated by Django 2.1 on 2019-03-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
