# Generated by Django 2.1 on 2019-03-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='quiz_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='topic_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
